version: '3.9'

services:
  nuture_bot_dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nuture_bot_dev
    env_file:
      - .env   
    ports:
      - "8000:8000"
    restart: always
